- hosts: localhost
  tasks:
  - name: "requirements install"
    shell: |
      cd ./backend/
      pip install -r ./requirements.txt
    become: yes
    register: result
  - debug:
      msg: "{{result}}"
